sudo: false
language: android
addons:
  apt:
    packages:
      - autoconf2.13
android:
  components:
    - android-23
    - build-tools-23.0.3
cache:
  apt: true
  ccache: true
env:
  global:
    - CCACHE_BASEDIR="$TRAVIS_BUILD_DIR"
    - MOZCONFIG="$TRAVIS_BUILD_DIR/external/tor-browser/.mozconfig-orfox-release"
    - SDK_BASE=/usr/local/android-sdk
    - versionCode="15"
    - versionName="Fennec-52.9.0esr/TorBrowser-7.5-2/Orfox-1.5.4-RC-1"
  matrix:
    - REV=10e
    #- REV=11c
    #- REV=12b
    #- REV=13b
    #- REV=14b
    #- REV=15c
    #- REV=16b
before_install:
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r$REV
  - export NDK_BASE=$ANDROID_NDK_HOME
  - if [ ! -f "$ANDROID_NDK_HOME/ndk-build" ]; then curl -L http://dl.google.com/android/repository/android-ndk-r$REV-linux-x86_64.zip -O; unzip -q android-ndk-r$REV-linux-x86_64.zip -d $HOME; fi
script:
  - cp .mozconfig-orfox-release $MOZCONFIG
  - cat external/tor-browser/.mozconfig-orfox >> $MOZCONFIG
  - cd external/tor-browser
  - ./mach configure
  - #./mach build
  - #sed -i "s,versionName=\"[^\"]*\",versionName=\"$versionName\"," obj-tbb-arm-linux-androideabi/mobile/android/base/AndroidManifest.xml
  - #sed -i "s,versionCode=\"[^\"]*\",versionCode=\"$versionCode\"," obj-tbb-arm-linux-androideabi/mobile/android/base/AndroidManifest.xml
  - #./mach package
after_failure:
- cat external/*/config.log
